/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicioAula03;

import java.util.ArrayList;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class EstoqueTest {
     private Estoque est;

     @BeforeEach
    public void criar(){
        est = new Estoque();
    }

    @Test
    public void testeAdicionar(){
    est.addProduto("uva", 6);
    assertEquals("uva",est.prodMoreEst());
    }

    @Test
    public void testeRemover(){
    est.addProduto("uva", 6);
    est.remProduto("uva", 1);
    assertEquals("uva",est.prodMoreEst());
    }

    @Test
    public void testeConferirQuantidade(){
    est.addProduto("uva", 6);
    est.consQntd("uva");
    assertEquals(6,est.consQntd("uva"));
    }

    @Test
    public void testeConferirQualOMaior(){
    est.addProduto("uva", 6);
    est.addProduto("banana", 8);
    assertEquals("banana",est.prodMoreEst());
    }    

    @Test
    public void testeLimpar(){
    ArrayList<Produto> vazia = new ArrayList<>();
    est.addProduto("uva", 6);
    est.limparEst();
    assertEquals(vazia,est.limparEst());
    }
    
    @Test
    public void testReabastecerEstoque() {
        est.addProduto("chocolate", 50);
        est.reabastecerEstoque(2);
        assertEquals(52, est.consQntd("chocolate"));
    }
    
    @Test 
    public void testListarProdutos() {
        est.addProduto("chocolate", 50);
        est.addProduto("toddynho", 30);
        assertEquals(" chocolate toddynho ", est.listarProdutos());
    }
}